---
title: "Linear Regression"
author: "By: Udit (based on ISLR)"
output: pdf_document
---

## Setup
```{r}
#library(MASS)
library(ISLR2)
```

## Simple Linear Regression
```{r}
names(Boston)
?Boston
plot(medv~lstat, Boston)

# Linear Model
fit1 = lm(medv~lstat, data=Boston)
summary(fit1)
confint(fit1)
abline(fit1, col="red")

predict(fit1, data.frame(lstat=c(5,10,15)), interval = "confidence")

```

## Multiple Linear Regression
```{r}
round(cor(Boston),2)

fit2 = lm(medv~lstat+age, data=Boston)
summary(fit2)

fit3 = lm(medv~., Boston)
summary(fit3)

par(mfrow=c(2,2))
plot(fit3)

fit4 = update(fit3, ~.-age-indus)
summary(fit4)
```

## Interactions Terms
```{r}
fit5 = lm(medv~lstat*age, Boston)
summary(fit5)

fit6 = lm(medv~lstat + I(lstat^2), Boston)
summary(fit6)
plot(fit6)

par(mfrow=c(1,1))
plot(medv~lstat, Boston)
points(Boston$lstat, fitted(fit6), col="red", pch=20)

fit7 = lm(medv~poly(lstat,4), Boston)
summary(fit7)
points(Boston$lstat, fitted(fit7), col="blue", pch=20)
#fix(Boston) #to view and edit data
```

## Qualitative Predictors
```{r}
names(Carseats)
summary(Carseats)

fit1 = lm(Sales~.+Income:Advertising+Age:Price, Carseats)
summary(fit1)

contrasts(Carseats$ShelveLoc)
```

## Writing R function
```{r}
regplot=function(x,y,...){
  fit = lm(y~x)
  plot(x,y,...)
  abline(fit, col="red")
}
regplot(Carseats$Price, Carseats$Sales)
regplot(Carseats$Price, Carseats$Sales, xlab="Price", ylab="Sales", col="blue", pch=20)
```
